# import the turtle module
import turtle as trtl

# create the turtle object
painter = trtl.Turtle()
color=input("What is your color?")
painter.pencolor(color)
painter.speed(15)
print("Let's play some kickball!")
painter.circle(50)
#penup make the turtle stop drawing
painter.penup()
painter.forward(200)
#makes the turtle start drawing
painter.pendown()
painter.circle(50)
painter.left(90)
painter.penup()
painter.forward(50)
painter.left(90)
painter.pendown()
painter.circle(10)
painter.penup()
painter.forward(200)
painter.pendown()
painter.circle(10)
painter.left(90)
painter.penup()
painter.forward(100)
painter.pendown()
painter.circle(50,180)
painter.penup()
painter.forward(50)
painter.pendown()
painter.circle(15)
painter.penup()
painter.left(90)
painter.forward(175)
painter.pendown()
painter.left(90)
painter.circle(200)
painter.penup()
painter.right(180)
painter.forward(200)
painter.right(90)
painter.forward(200)
painter.left(90)
painter.pendown()
painter.forward(100)
painter.right(180)
painter.forward(100)
painter.left(90)
painter.circle(50,90)
painter.penup()
painter.left(90)
painter.forward(50)
painter.left(90)
painter.forward(50)
painter.right(180)
painter.pendown()
painter.circle(50,90)
painter.penup()
painter.left(90)
painter.forward(450)
painter.left(90)
painter.forward(50)
painter.right(90)
painter.pendown()
painter.forward(150)
painter.left(45)
painter.forward(60)
painter.left(180)
painter.forward(60)
painter.left(90)
painter.forward(60)
painter.left(180)
painter.forward(60)
painter.left(45)
painter.forward(75)
painter.left(90)
painter.forward(50)
painter.right(45)
painter.forward(30)
painter.left(180)
painter.forward(30)
painter.left(45)
painter.forward(100)
painter.right(45)
painter.forward(30)
painter.pencolor("red")
painter.circle(10)

wn = trtl.Screen()
wn.mainloop()